upd

diff --git a/Daemon/nodejs/msg-server b/Daemon/nodejs/msg-server
--- a/Daemon/nodejs/msg-server
+++ b/Daemon/nodejs/msg-server
@@ -14,6 +14,7 @@ DAEMON="/usr/local/bin/node"
 ROOT_DIR="/opt/wmw/Daemon/nodejs"
  
 SERVER="$ROOT_DIR/cluster.js"
+APP="$ROOT_DIR/app.js"
 LOG_FILE="/var/log/$NAME.log"
 PID_FILE="/var/run/nodejs/$NAME.pid"
 LOCK_FILE="/var/lock/subsys/$NAME"
@@ -22,7 +23,7 @@ do_start()
 {
         if [ ! -f "$LOCK_FILE" ] ; then
                 echo -n $"Starting $SERVER: "
-                runuser -l "$USER" -c "$DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure
+                runuser -l "$USER" -c "$DAEMON $SERVER NODE_ENV >> $LOG_FILE &" && echo_success || echo_failure
                 RETVAL=$?
                 echo
                 [ $RETVAL -eq 0 ] && touch $LOCK_FILE
@@ -36,6 +37,8 @@ do_stop()
         echo -n $"Stopping $SERVER: "
         pid=`ps -aefw | grep "$DAEMON $SERVER" | grep -v " grep " | awk '{print $2}'`
         kill -9 $pid > /dev/null 2>&1 && echo_success || echo_failure
+        apppid=`ps -aefw | grep "$DAEMON $APP" | grep -v " grep " | awk '{print $2}'`
+        kill -9 $apppid > /dev/null 2>&1 && echo_success || echo_failure
         RETVAL=$?
         echo
         [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
